// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/interface/user.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	reflect "reflect"
	models "sample/pkg/utils/models"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserData mocks base method.
func (m *MockUserRepository) GetUserData(arg0 models.UserLoginDetails) (models.UserFeatchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserData", arg0)
	ret0, _ := ret[0].(models.UserFeatchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserData indicates an expected call of GetUserData.
func (mr *MockUserRepositoryMockRecorder) GetUserData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserData", reflect.TypeOf((*MockUserRepository)(nil).GetUserData), arg0)
}

// RepoGetUserName mocks base method.
func (m *MockUserRepository) RepoGetUserName(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoGetUserName", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// RepoGetUserName indicates an expected call of RepoGetUserName.
func (mr *MockUserRepositoryMockRecorder) RepoGetUserName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoGetUserName", reflect.TypeOf((*MockUserRepository)(nil).RepoGetUserName), arg0)
}

// SaveUserData mocks base method.
func (m *MockUserRepository) SaveUserData(arg0 models.UserDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserData indicates an expected call of SaveUserData.
func (mr *MockUserRepositoryMockRecorder) SaveUserData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserData", reflect.TypeOf((*MockUserRepository)(nil).SaveUserData), arg0)
}
